### PR TITLE
chore: Update write-file-atomic

### PR DESCRIPTION
**Pull request by coreyfarrell**
The intent is to release caching-transform@4.0.0 with this change.

### CODE REVIEW

**Comment by coreyfarrell** [comment]
write-file-atomic is semver-major for two reasons.

1. It now requires node.js 8 (caching-transform#master already requires node.js 8)
2. option.Promise has been removed (no effect here as we don't use the async interface)

So this is non-breaking for caching-transform (note no changes to any `*.js` file).  Technically it doesn't make much of a difference though as this repo has never followed conventional-commits, the release will be manual.  And yes I plan to use conventional-commits once this release is complete.

**Comment by JaKXz** [comment]
@coreyfarrell That's what I thought... That's why I think this should just be a patch release and be marked `fix: update write-file-atomic`.

**Comment by coreyfarrell** [comment]
We're already in a semver-major cycle, we haven't released since node.js 6 was dropped.

**Comment by JaKXz** [comment]
Ah - I didn't know that..

**Comment by coreyfarrell** [comment]
@JaKXz is this OK then?

**Pull request merged**
